#**MANIPULAÇÃO DE DADOS**

In [0]:
import pandas as pd

#1. Leitura de Arquivos

**1.1 Arquivos .csv e .txt**

pd.read_csv('nome_do_arquivo.extensão',sep='caractere_que_separa_os_dados',skiprows = numero_de_linhas_a_ser_puladas)

In [0]:
df_materiais = pd.read_csv('materiais.csv', sep = ';')

In [0]:
df_pedidos = pd.read_csv('pedidos.txt', sep = '|', skiprows = 2)

**1.2 Arquivos .xlsx**

pd.read_excel('nome_do_arquivo.extensão', sheet_name='nome_da_aba',skiprows = numero_de_linhas_a_ser_puladas)

In [0]:
df_vendas1 = pd.read_excel('vendas_1.xlsx', sheet_name = 'vendas')

In [0]:
df_vendas1

            Data  Material  Qtd.faturd
0     03.11.2019   6000110           1
1     03.11.2019   6000129           1
2     03.11.2019   6000163           1
3     03.11.2019   6000172           1
4     03.11.2019   6000892           1
...          ...       ...         ...
8652  05.11.2019   4005739           1
8653  05.11.2019   4005739           1
8654  05.11.2019   4005903           1
8655  05.11.2019   4005911           1
8656  05.11.2019   4005927           1

[8657 rows x 3 columns]

In [0]:
df_vendas2 = pd.read_excel('vendas_2.xlsx', sheet_name = 'vendas')

#2. Tratamento de Dados

**2.1 Renomear Colunas**

Colunas específicas

df.rename(columns={'coluna_antiga1': 'coluna_nova1','coluna_antiga2':'coluna_nova2'})

In [0]:
df_materiais = df_materiais.rename(columns={'Material':'material','Texto breve material':'texto_breve'})

Todas as colunas

df.columns = ['coluna_nova1','coluna_nova2']

In [0]:
df_pedidos.columns = ['fornecedor','material','qtd_pedido','texto_breve','qtd_estoque']

In [0]:
df_vendas1.columns = ['data','material','qtd_venda']

In [0]:
df_vendas2.columns = ['data','material','qtd_venda']

In [0]:
df_pedidos

                               fornecedor  ...  qtd_estoque
0     3593       SB COMERCIO LTDA          ...           12
1     3593       SB COMERCIO LTDA          ...            6
2     3593       SB COMERCIO LTDA          ...            5
3     3593       SB COMERCIO LTDA          ...            6
4     3593       SB COMERCIO LTDA          ...            2
...                                   ...  ...          ...
1064  4239       TAPAJOS COMERCIO DE MEDI  ...            0
1065  4239       TAPAJOS COMERCIO DE MEDI  ...            0
1066  4239       TAPAJOS COMERCIO DE MEDI  ...            0
1067  4239       TAPAJOS COMERCIO DE MEDI  ...            0
1068  4239       TAPAJOS COMERCIO DE MEDI  ...            0

[1069 rows x 5 columns]

**2.2 Verificar Tipos**

df.dtype           #Todas as colunas  |
df['coluna'].dtype #Coluna específica

In [0]:
df_materiais.dtypes

material        int64
texto_breve    object
dtype: object

In [0]:
df_pedidos.dtypes

fornecedor      object
material         int64
qtd_pedido     float64
texto_breve     object
qtd_estoque      int64
dtype: object

In [0]:
df_vendas1.dtypes

data         object
material      int64
qtd_venda     int64
dtype: object

Alterando tipo de uma coluna

df['coluna'].astype()

int, str, float

In [0]:
df_pedidos['qtd_pedido'] = df_pedidos['qtd_pedido'].astype(int)

In [0]:
df_pedidos.dtypes

fornecedor     object
material        int64
qtd_pedido      int64
texto_breve    object
qtd_estoque     int64
dtype: object

**2.3 Deletando Dados**

df.drop(['coluna2','coluna3'], axis = 'columns') #axis é o que vc quer apagar, linha ou coluna

df.drop([1,2], axis = 'index')

In [0]:
df_materiais

      material                                texto_breve
0      4000010   ALCACHOFRA 300MG CX 30CP
1      4000013   ANTI-SEPTICO ANESTESICO FRASCO 30ML
2      4000014   ASSEPTCARE SOL TOPICA FRASCO 30ML
3      4000015   ASSEPTCARE SOL TOPICA SPY FRASCO 50ML
4      4000016   BENATUX FRAMBOESA CX 12CP
...        ...                                        ...
4577   6001409  SABONETE LÃQ NIVEA NATURAL OIL 200ml
4578   6001410  SABONETE LÃQ NIVEA WATER LILY & OIL250ml
4579   6001411  TÃNICO NIVEA CONT BRILHO 200ml
4580   6001412  TÃNICO NIVEA PROTETOR FACIAL 200ml
4581   6001415   CHOCOLATE KINDER BUENO WHITE-CX30

[4582 rows x 2 columns]

In [0]:
df_materiais = df_materiais.drop(['texto_breve'],axis='columns')

In [0]:
df_materiais

      material
0      4000010
1      4000013
2      4000014
3      4000015
4      4000016
...        ...
4577   6001409
4578   6001410
4579   6001411
4580   6001412
4581   6001415

[4582 rows x 1 columns]

df[['coluna1','coluna2']].copy() #.copy apenas omite o que não queremos ver

In [0]:
df_pedidos = df_pedidos[['material','qtd_estoque','qtd_pedido']].copy()

In [0]:
df_pedidos

      material  qtd_estoque  qtd_pedido
0      4003232           12         120
1      4005091            6          60
2      4003225            5          51
3      4003251            6          60
4      4001716            2          20
...        ...          ...         ...
1064   4000333            0           1
1065   4003698            0           1
1066   4000359            0           1
1067   4005114            0           1
1068   4003731            0           1

[1069 rows x 3 columns]

In [0]:
df_vendas1 = df_vendas1.drop(['data'],axis='columns')

In [0]:
df_vendas1

      material  qtd_venda
0      6000110          1
1      6000129          1
2      6000163          1
3      6000172          1
4      6000892          1
...        ...        ...
8652   4005739          1
8653   4005739          1
8654   4005903          1
8655   4005911          1
8656   4005927          1

[8657 rows x 2 columns]

In [0]:
df_vendas2 = df_vendas2[['material','qtd_venda']].copy()

In [0]:
df_vendas2

      material  qtd_venda
0      6001085          1
1      4000020          1
2      4000020          1
3      4000020          1
4      4000045          1
...        ...        ...
8139   6000768          1
8140   6000839          1
8141   6000843          1
8142   6000969          1
8143   6000400          1

[8144 rows x 2 columns]

#3. Concatenação de Tabelas

pd.concat([tabela1,tabela2,...])

In [0]:
df_vendas1.shape  #mostra a quantidade de linhas e colunas

(8657, 2)

In [0]:
df_vendas2.shape

(8144, 2)

In [0]:
df_vendas = pd.concat([df_vendas1,df_vendas2])

In [0]:
df_vendas = df_vendas.reset_index(drop=True)

In [0]:
df_vendas

       material  qtd_venda
0       6000110          1
1       6000129          1
2       6000163          1
3       6000172          1
4       6000892          1
...         ...        ...
16796   6000768          1
16797   6000839          1
16798   6000843          1
16799   6000969          1
16800   6000400          1

[16801 rows x 2 columns]

#4. Correlação de Tabelas

**4.1 Agrupamento de dados**

df.groupby('coluna a ser agrupada']).agg({'coluna1':'sum','coluna2':'mean','coluna3':'max',...}).reset_index()

In [0]:
df_vendas = df_vendas.groupby(['material']).agg({'qtd_venda':'sum'}).reset_index()

In [0]:
df_vendas

      material  qtd_venda
0      4000013          6
1      4000014          1
2      4000015          8
3      4000016          3
4      4000017          6
...        ...        ...
2937   6001403          8
2938   6001404          3
2939   6001405          4
2940   6001409          2
2941   6001415         14

[2942 rows x 2 columns]

In [0]:
df_pedidos = df_pedidos.groupby(['material']).agg({'qtd_estoque':'sum','qtd_pedido':'sum'}).reset_index()

In [0]:
df_pedidos

     material  qtd_estoque  qtd_pedido
0     4000010           25         250
1     4000014            6          60
2     4000019            0           7
3     4000020            0           9
4     4000047            5          50
..        ...          ...         ...
938   6001069            1          12
939   6001074            4          42
940   6001075            0           2
941   6001078            1          16
942   6001415            0           4

[943 rows x 3 columns]

**4.2 Merge**

pd.merge(tabela_esquerda,tabela_direita, on = ['coluna em comum'], how = 'método')

metodo poe ser: left(esquerda), right(direita), inner(itens em comum), outer (todos os itens)

In [0]:
df_relatorio = pd.merge(df_materiais, df_pedidos, on = ['material'], how = 'left')

In [0]:
df_relatorio

      material  qtd_estoque  qtd_pedido
0      4000010         25.0       250.0
1      4000013          NaN         NaN
2      4000014          6.0        60.0
3      4000015          NaN         NaN
4      4000016          NaN         NaN
...        ...          ...         ...
4577   6001409          NaN         NaN
4578   6001410          NaN         NaN
4579   6001411          NaN         NaN
4580   6001412          NaN         NaN
4581   6001415          0.0         4.0

[4582 rows x 3 columns]

In [0]:
df_relatorio = pd.merge(df_relatorio, df_vendas, on = ['material'], how = 'left')

**4.3 Tratamento pós merge**

In [0]:
df_relatorio = df_relatorio.fillna(0)

In [0]:
df_relatorio[['qtd_estoque','qtd_pedido','qtd_venda']] = df_relatorio[['qtd_estoque','qtd_pedido','qtd_venda']].astype(int)

In [0]:
df_relatorio

      material  qtd_estoque  qtd_pedido  qtd_venda
0      4000010           25         250          0
1      4000013            0           0          6
2      4000014            6          60          1
3      4000015            0           0          8
4      4000016            0           0          3
...        ...          ...         ...        ...
4577   6001409            0           0          2
4578   6001410            0           0          0
4579   6001411            0           0          0
4580   6001412            0           0          0
4581   6001415            0           4         14

[4582 rows x 4 columns]

#5. Regra de Negócio

Operações entre colunas sem condicional

In [0]:
df_relatorio['qtd_loja'] = df_relatorio['qtd_estoque'] + df_relatorio['qtd_pedido']

In [0]:
df_relatorio = df_relatorio[['material','qtd_loja','qtd_venda']].copy()

Operações entre colunas com condicional

In [0]:
def calcular_porcentagem(loja,venda):
    if (venda!=0):
        return loja/venda
    elif (venda==0) and (loja!=0):
        return 1.2
    else:
        return 0

df.apply(lambda row: funcao(row['coluna']), axis='columns')

In [0]:
df_relatorio['porcentagem'] = df_relatorio.apply(lambda row: calcular_porcentagem(row['qtd_loja'],row['qtd_venda']), axis = 'columns')

In [0]:
def verificar_status(porc):
  if (porc>=1.2):
    return 'alerta'
  else:
    return ''

In [0]:
df_relatorio['status'] = df_relatorio.apply(lambda row: verificar_status(row['porcentagem']),axis= 'columns')

#Filtro

df[(condicao)]

and -> & or -> |

In [0]:
df_relatorio = df_relatorio[(df_relatorio['status']!='alerta') & (df_relatorio['qtd_loja']!=0)]

#Ordenando Valores

df.sort_values(['colunas a serem ordenadas'], ascending=True) -> ordem crescente

df.sort_values(['colunas a serem ordenadas'], ascending=False) -> ordem decrescente

In [0]:
df_relatorio = df_relatorio.sort_values(['qtd_loja'], ascending=False)

#6. Exportando Arquivo

**.CSV**

df.to_csv('nome_relatorio.csv', sep='caracter que vai separar os dados', index=False)

In [0]:
df_relatorio.to_csv('Relatório Final.csv', sep=';', index=False)

**.XLSX**

writer = pd.ExcelWriter('nome_relatorio.xlsx')

df.to_excel(writer, sheet_name='nome da aba', index=False)

df2.to_excel(writer, sheet_name='nome da aba2', index=False)

writer.save()

In [0]:
writer = pd.ExcelWriter('Relatório Final.xlsx')

df_relatorio.to_excel(writer, sheet_name='relatorio', index=False)
df_materiais.to_excel(writer, sheet_name='materiais', index=False)
df_pedidos.to_excel(writer, sheet_name='pedidos',index=False)
df_vendas.to_excel(writer, sheet_name='vendas', index=False)

writer.save()